package model.services;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 13 10:12:20 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for POCHeaderView1.
     * @return POCHeaderView1
     */
    public ViewObjectImpl getPOCHeaderView1() {
        return (ViewObjectImpl)findViewObject("POCHeaderView1");
    }

    /**
     * Container's getter for pocSearchVo1.
     * @return pocSearchVo1
     */
    public ViewObjectImpl getpocSearchVo1() {
        return (ViewObjectImpl)findViewObject("pocSearchVo1");
    }
}
